auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: ChikoritaPiplup
url: http://chikoritapiplup.github.io
feed: /atom.xml
author_info: <a href="http://chikoritapiplup.github.io/">ChikoritaPiplup</a>
